### ISSUE TITLE
Improve notifications

### ISSUE THREAD

**Issue by avdata99** [ckan/ckanext-harvest#406]
As an admin of an organization that relies heavily on harvesting, I want the option to receive job completion summaries for all jobs (not just errors), so that I'm notified of **all** changes related to harvest jobs.

I think it would be helpful for some users of this extension to have the option to enable summary email notifications, which would be very similar to the error email, only with some extra information (records added, updated, deleted, and a list of those packages). 

A simple implementation of this _could_ be: rename `send_error_mail` to something like `send_summary_mail` or `send_notification` (and make it a universal report template, or we can create a new function for summaries), add the extra records information, and add a new `.env` variable option like `ckanext.harvest.status_mail.summary` (leaving the option for error only mail as well).

**Tasks**
 - [x] Add a new config value to send notifications for all jobs
 - [x] Rename the _send_error_mail_ and use it for all jobs (if we set this up)
 - [x] Add test to cover this change  

**Notes**
I already start working on this.

**Comment by amercader** [comment]
Sounds very useful, thanks @avdata99 
From what I understood rather than renaming `send_error_mail` I think we should abstract all logic relating to sending the email to a parent `send_email` function and then call `send_error_email` and `send_summary_email` from the relevant places, as they will be called on different occasions. Ideally `send_email` would just receive the content and the subject and it would be up to the callers to build them and provide them.
As a suggestion, a nice improvement would be to rely on templates to build the email body rather than building a string like `send_error_mail` does now. This would make it more readable and allow extensions to customize the email sent.

**Comment by avdata99** [comment]
@amercader I sent PR #407 which cover this issue
Let me know if you or someone at this harvest team could review it
